@baseUrl = http://icon.smartisan.com/drawable/
@json = content-type: application/json

### 根据包名获取icon链接
POST http://setting.smartisan.com/app/icon/ HTTP/1.1
{{json}}

[{"package":"com.tencent.qqmusic"}]

#http://icon.smartisan.com/info/com.tencent.qqmusic/icon_provided_by_smartisan.xml
#http://icon.smartisan.com/drawable/com.tencent.qqmusic/icon_provided_by_smartisan.png
### 
POST {{baseUrl}} HTTP/1.1
{{json}}

